"""Added Activation Code field

Revision ID: 8286d06f0db4
Revises: 00ab69b14f5a
Create Date: 2023-01-03 00:15:54.942147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8286d06f0db4'
down_revision = '00ab69b14f5a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptionplan', sa.Column('plan_name', sa.String(length=36), nullable=False))
    op.add_column('users', sa.Column('activation_code', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('resgistration_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'resgistration_date')
    op.drop_column('users', 'activation_code')
    op.drop_column('subscriptionplan', 'plan_name')
    # ### end Alembic commands ###
