"""Staff Tasks Model

Revision ID: 102e6c941ce3
Revises: 927c04e47c73
Create Date: 2023-01-26 23:16:58.234381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '102e6c941ce3'
down_revision = '927c04e47c73'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stafftask',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('staff_id', sa.String(length=36), nullable=True),
    sa.Column('task_title', sa.String(length=36), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('valid_for', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staffmember.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stafftask')
    # ### end Alembic commands ###
