"""Added Nullable fields

Revision ID: 2690c51cd7c3
Revises: 8f83356fde10
Create Date: 2023-01-09 18:14:32.768017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2690c51cd7c3'
down_revision = '8f83356fde10'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
