"""Removed relationships

Revision ID: 2709cda07ab6
Revises: 39d977f7e64e
Create Date: 2023-01-09 18:46:44.197848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2709cda07ab6'
down_revision = '39d977f7e64e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
