"""Added extra fields to user model

Revision ID: 377ebc553111
Revises: 90dd09588ca6
Create Date: 2023-01-05 11:10:04.386905

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '377ebc553111'
down_revision = '90dd09588ca6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptionplan', sa.Column('min_members', sa.Float(), nullable=True))
    op.add_column('subscriptionplan', sa.Column('max_members', sa.Float(), nullable=True))
    op.drop_column('subscriptionplan', 'members')
    op.add_column('users', sa.Column('profile_image_url', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('plan_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'users', 'subscriptionplan', ['plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'plan_id')
    op.drop_column('users', 'profile_image_url')
    op.add_column('subscriptionplan', sa.Column('members', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('subscriptionplan', 'max_members')
    op.drop_column('subscriptionplan', 'min_members')
    # ### end Alembic commands ###
