"""Added foreign key tags

Revision ID: 39d977f7e64e
Revises: 2690c51cd7c3
Create Date: 2023-01-09 18:41:22.256606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39d977f7e64e'
down_revision = '2690c51cd7c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
