"""Attendance Model added

Revision ID: 5e44b630c171
Revises: b3fdda8b6ddd
Create Date: 2023-01-21 16:51:21.698991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e44b630c171'
down_revision = 'b3fdda8b6ddd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staffattendance',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('staff_id', sa.String(length=36), nullable=True),
    sa.Column('in_time', sa.Time(), nullable=True),
    sa.Column('out_time', sa.Time(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staffmember.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staffattendance')
    # ### end Alembic commands ###
