"""Dropped 2 parent  constraint

Revision ID: 63bac9a652f2
Revises: 6b9a572256ef
Create Date: 2023-01-18 12:11:02.622966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63bac9a652f2'
down_revision = '6b9a572256ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('familymember', sa.Column('parent_email', sa.String(length=36), nullable=True))
    op.drop_constraint('familymember_second_parent_email_fkey', 'familymember', type_='foreignkey')
    op.drop_constraint('familymember_first_parent_email_fkey', 'familymember', type_='foreignkey')
    op.create_foreign_key(None, 'familymember', 'users', ['parent_email'], ['email'])
    op.drop_column('familymember', 'second_parent_email')
    op.drop_column('familymember', 'first_parent_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('familymember', sa.Column('first_parent_email', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.add_column('familymember', sa.Column('second_parent_email', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'familymember', type_='foreignkey')
    op.create_foreign_key('familymember_first_parent_email_fkey', 'familymember', 'users', ['first_parent_email'], ['email'])
    op.create_foreign_key('familymember_second_parent_email_fkey', 'familymember', 'users', ['second_parent_email'], ['email'])
    op.drop_column('familymember', 'parent_email')
    # ### end Alembic commands ###
