"""Changes

Revision ID: 6bc0b992f2fc
Revises: a5675ed0d0d7
Create Date: 2023-02-21 11:58:31.122095

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6bc0b992f2fc'
down_revision = 'a5675ed0d0d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staffabsence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('staff_id', sa.String(length=36), nullable=True),
    sa.Column('abscence_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staffmember.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('StaffAbsence')
    op.add_column('stafftask', sa.Column('valid_till', sa.DateTime(), nullable=True))
    op.drop_column('stafftask', 'valid_for')
    op.drop_constraint('subscribergroup_plan_id_fkey', 'subscribergroup', type_='foreignkey')
    op.create_foreign_key(None, 'subscribergroup', 'subscriptionplan', ['plan_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscribergroup', type_='foreignkey')
    op.create_foreign_key('subscribergroup_plan_id_fkey', 'subscribergroup', 'subscriptionplan', ['plan_id'], ['id'])
    op.add_column('stafftask', sa.Column('valid_for', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('stafftask', 'valid_till')
    op.create_table('StaffAbsence',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('staff_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('abscence_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staffmember.id'], name='StaffAbsence_staff_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='StaffAbsence_pkey')
    )
    op.drop_table('staffabsence')
    # ### end Alembic commands ###
