"""Scheduler Log

Revision ID: 758320eafb48
Revises: df4e619e2c98
Create Date: 2023-01-19 13:40:51.798134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '758320eafb48'
down_revision = 'df4e619e2c98'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedulerlog',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_name', sa.String(length=128), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('log', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedulerlog_job_name'), 'schedulerlog', ['job_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedulerlog_job_name'), table_name='schedulerlog')
    op.drop_table('schedulerlog')
    # ### end Alembic commands ###
