"""Added Employment Status

Revision ID: 880f370bd7fd
Revises: badfe11693e9
Create Date: 2023-01-23 12:19:46.711145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '880f370bd7fd'
down_revision = 'badfe11693e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('StaffAbsence',
                    sa.Column('id', sa.String(length=36), nullable=False),
                    sa.Column('staff_id', sa.String(length=36), nullable=True),
                    sa.Column('abscence_date', sa.Date(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['staff_id'], ['staffmember.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('staffmember', sa.Column(
        'employment_status', sa.String(length=24), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staffmember', 'employment_status')
    op.drop_table('StaffAbsence')
    # ### end Alembic commands ###
