"""Added FKs

Revision ID: 8f83356fde10
Revises: 98a99c6d2474
Create Date: 2023-01-09 18:12:52.164570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f83356fde10'
down_revision = '98a99c6d2474'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscriber_group_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'users', 'subscribergroup', ['subscriber_group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'subscriber_group_id')
    # ### end Alembic commands ###
