"""check in check out attributes

Revision ID: 927c04e47c73
Revises: 880f370bd7fd
Create Date: 2023-01-24 10:17:22.060985

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '927c04e47c73'
down_revision = '880f370bd7fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staffabsence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('staff_id', sa.String(length=36), nullable=True),
    sa.Column('abscence_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staffmember.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.drop_table('staffabscence')
    op.add_column('staffattendance', sa.Column('check_in_time', sa.Time(), nullable=True))
    op.add_column('staffattendance', sa.Column('check_out_time', sa.Time(), nullable=True))
    op.drop_column('staffattendance', 'out_time')
    op.drop_column('staffattendance', 'in_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staffattendance', sa.Column('in_time', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('staffattendance', sa.Column('out_time', postgresql.TIME(), autoincrement=False, nullable=True))
    op.drop_column('staffattendance', 'check_out_time')
    op.drop_column('staffattendance', 'check_in_time')
    op.create_table('staffabscence',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('staff_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('abscence_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staffmember.id'], name='staffabscence_staff_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='staffabscence_pkey')
    )
    op.drop_table('staffabsence')
    # ### end Alembic commands ###
