"""Chats Models

Revision ID: 94181ec956dd
Revises: d0979e76cc67
Create Date: 2023-02-04 19:50:30.676235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94181ec956dd'
down_revision = 'd0979e76cc67'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chat_id', sa.String(length=64), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('sender', sa.String(length=36), nullable=True),
    sa.Column('time_stamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chatroom',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('first_user_email', sa.String(length=36), nullable=True),
    sa.Column('secoond_user_email', sa.String(length=36), nullable=True),
    sa.Column('chat_id', sa.String(length=64), nullable=False),
    sa.Column('last_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['first_user_email'], ['users.email'], ),
    sa.ForeignKeyConstraint(['secoond_user_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chatroom')
    op.drop_table('chats')
    # ### end Alembic commands ###
