"""Staff tasks Mapping

Revision ID: a0afa5c951cb
Revises: 102e6c941ce3
Create Date: 2023-01-27 18:13:25.469705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0afa5c951cb'
down_revision = '102e6c941ce3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stafftaskmapping',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('staff_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staffmember.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['stafftask.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('stafftask', sa.Column('valid_from', sa.DateTime(), nullable=True))
    op.add_column('stafftask', sa.Column('priority', sa.String(length=24), nullable=False))
    op.add_column('stafftask', sa.Column('status', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_stafftask_task_title'), 'stafftask', ['task_title'], unique=False)
    op.drop_constraint('stafftask_staff_id_fkey', 'stafftask', type_='foreignkey')
    op.drop_column('stafftask', 'staff_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stafftask', sa.Column('staff_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.create_foreign_key('stafftask_staff_id_fkey', 'stafftask', 'staffmember', ['staff_id'], ['id'])
    op.drop_index(op.f('ix_stafftask_task_title'), table_name='stafftask')
    op.drop_column('stafftask', 'status')
    op.drop_column('stafftask', 'priority')
    op.drop_column('stafftask', 'valid_from')
    op.drop_table('stafftaskmapping')
    # ### end Alembic commands ###
