"""Changes in subscriber group model

Revision ID: abd9fb751f40
Revises: 2709cda07ab6
Create Date: 2023-01-09 21:58:07.835022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abd9fb751f40'
down_revision = '2709cda07ab6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribergroup', sa.Column('admin_email', sa.String(length=36), nullable=True))
    op.drop_constraint('subscribergroup_admin_fkey', 'subscribergroup', type_='foreignkey')
    op.create_foreign_key(None, 'subscribergroup', 'users', ['admin_email'], ['email'])
    op.drop_column('subscribergroup', 'admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribergroup', sa.Column('admin', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'subscribergroup', type_='foreignkey')
    op.create_foreign_key('subscribergroup_admin_fkey', 'subscribergroup', 'users', ['admin'], ['email'])
    op.drop_column('subscribergroup', 'admin_email')
    # ### end Alembic commands ###
