"""Resset Password Model

Revision ID: c0c9b18ddb29
Revises: abd9fb751f40
Create Date: 2023-01-10 15:33:02.252656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0c9b18ddb29'
down_revision = 'abd9fb751f40'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resetpasswordrequest',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_email', sa.String(length=32), nullable=True),
    sa.Column('reset_code', sa.Float(), nullable=True),
    sa.Column('validity', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resetpasswordrequest_reset_code'), 'resetpasswordrequest', ['reset_code'], unique=False)
    op.create_index(op.f('ix_resetpasswordrequest_user_email'), 'resetpasswordrequest', ['user_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resetpasswordrequest_user_email'), table_name='resetpasswordrequest')
    op.drop_index(op.f('ix_resetpasswordrequest_reset_code'), table_name='resetpasswordrequest')
    op.drop_table('resetpasswordrequest')
    # ### end Alembic commands ###
