"""Dropped id from unique constraint

Revision ID: df4e619e2c98
Revises: 63bac9a652f2
Create Date: 2023-01-18 12:58:19.608580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df4e619e2c98'
down_revision = '63bac9a652f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
